[theme]
primaryColor = "#003B8E"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"
[server]
headless = true
[browser]
gatherUsageStats = false
